services:
  # PHP-FPM
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lcp_php
    volumes:
      - .:/var/www/html
    networks:
      - laraveldockerize

  # Nginx
  webserver:
    image: nginx:1.19-alpine
    container_name: lcp_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./dockerize/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laraveldockerize

  # MySQL
  mysql:
    image: mysql:8.4
    container_name: lcp_mysql
    restart: unless-stopped
    ports:
      - "3307:3306" # Avoid conflict with XAMPP MySQL
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laraveldockerize

  # Composer
  composer:
    image: composer:2.4
    container_name: lcp_composer
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - laraveldockerize

  # Node/NPM
  npm:
    image: node:18-alpine
    container_name: lcp_npm
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - laraveldockerize

volumes:
  mysql_data:


networks:
  laraveldockerize:
